"""gorevlere en erken baslangic tarihi

Revision ID: 6fdaf2550579
Revises: 7c1cf5914b88
Create Date: 2026-07-30 16:46:56.783161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdaf2550579'
down_revision: Union[str, Sequence[str], None] = '7c1cf5914b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('en_erken_baslangic', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'en_erken_baslangic')
    # ### end Alembic commands ###
