"""task_yeni_alanlar_profil_ve_plan_kayitlari

Tasks tablosuna duration_minutes/completed_at/postponement_count eklenir;
Profil (tekil ayar profili) ve plan_kayitlari (plan üretim geçmişi) tabloları
oluşturulur. Mevcut task satırları duration_minutes=30, postponement_count=0
ile backfill edilir; completed_at NULL kalır (geçmişte ne zaman tamamlandığı
bilinmiyor — kabul edilen MVP sınırlaması).

Revision ID: 7d45f9b9fe21
Revises: 6266eef77d6e
Create Date: 2026-07-27 15:56:48.913964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d45f9b9fe21'
down_revision: Union[str, Sequence[str], None] = '6266eef77d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gun', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dilimler', sa.JSON(), nullable=False),
    sa.Column('toplam_is_dakika', sa.Integer(), nullable=False),
    sa.Column('bos_zaman_dakika', sa.Integer(), nullable=False),
    sa.Column('genel_tavsiye', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_kayitlari_gun'), 'plan_kayitlari', ['gun'], unique=False)
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=200), nullable=False),
    sa.Column('e_posta', sa.String(length=200), nullable=False),
    sa.Column('verimli_baslangic', sa.Time(), nullable=False),
    sa.Column('verimli_bitis', sa.Time(), nullable=False),
    sa.Column('uyku_baslangic', sa.Time(), nullable=False),
    sa.Column('uyku_bitis', sa.Time(), nullable=False),
    sa.Column('gunluk_hedef', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('duration_minutes', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('postponement_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'postponement_count')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'duration_minutes')
    op.drop_table('profil')
    op.drop_index(op.f('ix_plan_kayitlari_gun'), table_name='plan_kayitlari')
    op.drop_table('plan_kayitlari')
    # ### end Alembic commands ###
